name: CI

on:
  push:

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - uses: Swatinem/rust-cache@v2

      - name: Test
        run: cargo test --workspace

      - name: Documentation
        run: cargo doc --workspace --no-deps
        env:
          RUSTDOCFLAGS: -D warnings

      - name: Clippy
        continue-on-error: true
        run: cargo clippy --workspace --all-targets

      - name: Formatting
        continue-on-error: true
        run: cargo fmt --check
